# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Train Finder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Train Finder
pod 'Overcoat'
  pod 'AFNetworking'
  pod 'AFNetworking/UIKit'
#  pod 'PromiseKit'

  target 'Train FinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
